config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'generic#landing'

	# These routes will be for signup. The first renders a form in the browse, the second will 
	# receive the form and create a user in our database using the data given to us by the user.
	post '/recruiters' => 'recruiters#create'

	post '/login' => 'sessions#create', :as => :create_session
	get '/logout' => 'sessions#destroy'

	resources :companies do
	end

	resources :vacancies do
		get '/interview' => 'vacancies#interview', :as => :interview
		get '/interview/results' => 'vacancies#results', :as => :interview_results
	end

	post '/vacancies/:vacancy_id/jobseeker_vacancies' => 'jobseeker_vacancies#create', :as => :create_match

	resources :jobseekers do
	end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
	belongs_to :company
	belongs_to :recruiter
  has_many :jobseeker_vacancies
  has_many :jobseekers, through: :jobseeker_vacancies

	DEPARTMENT_LIST = [
  	'Accounting & Finance',
  	'Administrative & Management',
  	'Communications & Public Relations',
  	'Customer Service Support',
  	'Distribution & Logistics',
  	'Human Resource & Talent',
  	'IT & Tech',
  	'Legal',
  	'Marketing & Sales',
  	'Operations & Production',
  	'Research & Development'
  ]

  QUESTION_LIST = [
    'Why do you want this job?',
    'What do you know about the company?',
    'What are your greatest professional strengths?',
    'What do you consider to be your weaknesses?',
    'Tell me how you dealt with the biggest challenge in university?',
    'Where do you see yourself in five years?',
    'What type of work environment do you prefer?',
    'How do you deal with pressure or stressful situations?',
    'What would your first 30, 60, or 90 days look like in this role?'
  ]
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
	def new
		@vacancy = Vacancy.new
	end

	def create
		@vacancy = Vacancy.new(vacancy_params)
		@vacancy.recruiter_id = current_recruiter.id
		@company = Company.find_by(recruiter_id: current_recruiter.id)
		@vacancy.company_id = @company.id
		if @vacancy.save
			redirect_to vacancy_path(@vacancy)
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def show
		@vacancy = Vacancy.find(params[:id])
		@company = Company.find(@vacancy.company.id)
		@degrees = Industry.all
		@knowledges = Topic.all
		@skills = Skill.all
		@activities = Activity.all
		@matches = JobseekerVacancy.where(vacancy_id: params[:id])

	  	if params[:degree] 
	      	@jobseekers = Jobseeker.where(location_id: @company.state).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry).where(degree_id: params[:degree])
	    elsif params[:knowledge]
	    	@jobseekers = Jobseeker.where(location_id: @company.state).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry).where(top_knowledge_id: params[:knowledge])
	    elsif params[:activity]
	    	@jobseekers = Jobseeker.where(location_id: @company.state).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry).where(top_knowledge_id: params[:activity])
	    elsif params[:skill]
    		@jobseekers = Jobseeker.where(location_id: @company.state).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry).where(top_knowledge_id: params[:skill])
    	else
			@jobseekers = Jobseeker.where(location_id: @company.state).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
	    end

	    @match = JobseekerVacancy.new
	end

	def interview
		@vacancy = Vacancy.find(params[:vacancy_id])
		@company = Company.find(@vacancy.company.id)
		@matches = JobseekerVacancy.where(vacancy_id: @vacancy.id)	
	end

	def update
		@vacancy = Vacancy.find(params[:id])
		if @vacancy.update(vacancy_params)
			redirect_to company_path(current_recruiter)
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def results
		@vacancy = Vacancy.find(params[:vacancy_id])
		@company = Company.find(@vacancy.company.id)
		@matches = JobseekerVacancy.where(vacancy_id: @vacancy.id)
	end

	private

	def vacancy_params
	  params.require(:vacancy).permit!
	end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/interview.html.erb
<div style="margin: 10px;">
	<div style="background-color: yellow">
		<h3>NOTES FOR DEMONSTRATION</h3>
		<ol>
		</ol>
	</div>

	<div>
		<h3>Company Profile</h3>
		<div style="margin-bottom: 5px;">
			Name: <%= @company.name %><br>
			Industry: <%= @company.industry.name %><br>
			Size: <%= @company.workforce_size %><br>
			Preference of talent work hours: <%= @company.work_hours %><br>
			Preference of talent strength: <%= @company.strength %><br>
		</div>
	</div>

	<br>

	<div>
		<h3>Vacancy Details</h3>
		<div style="margin-bottom: 5px;">
			Role: <%= @vacancy.name %><br>
			Description: <%= @vacancy.description %><br>
			Department: <%= @vacancy.department %><br>
			Quantity Needed: <%= @vacancy.quantity %><br>
		</div>
	</div>

	<div style="border: 2px blue solid; padding: 2px; margin-bottom: 5px;">
		<div class="text-center">
			<h4>Interview Pool: <%= @matches.count %> jobseekers</h4>
		</div>
		<div class="container-fluid" style="font-size: 15px;">
		    <div class="row">
		    	<% @matches.each do |match|%>
			        <div class="col-sm-6 col-lg-3 py-2">
			            <div class="card h-100" style="background-color: lightgreen">
			                <div class="card-body">
			                    <h4 class="card-title">Candidate Number: <%= match.jobseeker.id %></h4>
			                    <p class="card-text">
									Degree in: <%= match.jobseeker.degree.name %><br>
									University: <%= match.jobseeker.university.name %><br>
									Latest CGPA: <%= match.jobseeker.cgpa %><br>
									Knowledge Score: <%= match.jobseeker.knowledge_score %>%<br>
									Skill Score: <%= match.jobseeker.skill_score %>%<br>
									Activity Score: <%= match.jobseeker.activity_score %>%<br>
			                    	</p>
			                    <p class="card-text"><small class="text-muted">Last Updated: <%= match.jobseeker.created_at.to_date %></small></p>
			                </div>
			            </div>
			        </div>
			    <% end %>
		    </div>
		</div>
	</div>


	<div style="border: 2px blue solid; padding: 5px;">
		<h4>Choose your interview questions!</h4>
		<h6>You can choose between 5-10 questions with a total duration of 120 seconds!</h6>
		<div>
			<%=form_for @vacancy do |form|%>
				<div>
					<%= form.label :question_1 %> 
					<%= form.select(:question_1, Vacancy::QUESTION_LIST, {:required => true}) %>

					<%= form.select :q1_time, ((10..30).step(5).map {|i| [i,i] } << [40,10]) %>
					<%= form.label :seconds %> 
				</div>

				<div>
					<%= form.label :question_2 %> 
					<%= form.select(:question_2, Vacancy::QUESTION_LIST, {:required => true}) %>

					<%= form.select :q2_time, ((10..30).step(5).map {|i| [i,i] } << [40,10]) %>
					<%= form.label :seconds %> 
				</div>
				<div>
					<%= form.label :question_3 %> 
					<%= form.select(:question_3, Vacancy::QUESTION_LIST, {:required => true}) %>

					<%= form.select :q3_time, ((10..30).step(5).map {|i| [i,i] } << [40,10]) %>
					<%= form.label :seconds %> 
				</div>
				<div>
					<%= form.label :question_4 %>
					<%= form.select(:question_4, Vacancy::QUESTION_LIST, {:required => true}) %>

					<%= form.select :q4_time, ((10..30).step(5).map {|i| [i,i] } << [40,10]) %>
					<%= form.label :seconds %> 
				</div>
				<div>
					<%= form.label :question_5 %> 
					<%= form.select(:question_5, Vacancy::QUESTION_LIST, {:required => true}) %>

					<%= form.select :q5_time, ((10..30).step(5).map {|i| [i,i] } << [40,10]) %>
					<%= form.label :seconds %> 
				</div>			
			
				<%=form.submit 'Submit Interview Questions!'%>
			<% end %>
		</div>
	</div>

</div>

app/views/vacancies/new.html.erb
<div style="margin: 10px;">
	<div style="background-color: yellow">
		<h3>NOTES FOR DEMONSTRATION</h3>
		<ol>
			<li>This is where recruiter create a new vacancy to hire. Equivalent to job posting.</li>
			<li>No charges at this point.</li>
		</ol>
	</div>

	<div>
		<h3>Create a specific vacancy!</h3>
	</div>

	<div>
		<div>

			<%=form_for @vacancy do |form|%>
				<div>
					<%= form.label :name %> 
					<%= form.text_field :name, placeholder: 'Name of Role' %>
				</div>
				
				<div>
					<%= form.label :description %> 
					<%= form.text_field :description, placeholder: 'Describe this role' %>
				</div>

				<div>
					<%= form.label :department %> 
					<%= form.select(:department, Vacancy::DEPARTMENT_LIST, {:required => true}) %>
				</div>

				<div>
					<%= form.label :quantity %> 
					<%= form.select :quantity, ((1..9).map {|i| [i,i] } << [10,nil]) %>
				</div>
			
				<%=form.submit%>
			<% end %>
		</div>
	</div>
</div>

app/views/vacancies/results.html.erb
<div style="margin: 10px;">
	<div style="background-color: yellow">
		<h3>NOTES FOR DEMONSTRATION</h3>
		<ol>
		</ol>
	</div>

	<div>
		<h3>Company Profile</h3>
		<div style="margin-bottom: 5px;">
			Name: <%= @company.name %><br>
			Industry: <%= @company.industry.name %><br>
			Size: <%= @company.workforce_size %><br>
			Preference of talent work hours: <%= @company.work_hours %><br>
			Preference of talent strength: <%= @company.strength %><br>
		</div>
	</div>

	<br>

	<div>
		<h3>Vacancy Details</h3>
		<div style="margin-bottom: 5px;">
			Role: <%= @vacancy.name %><br>
			Description: <%= @vacancy.description %><br>
			Department: <%= @vacancy.department %><br>
			Quantity Needed: <%= @vacancy.quantity %><br>
		</div>
	</div>

	<div style="border: 2px blue solid; padding: 2px; margin-bottom: 5px;">
		<div class="text-center">
			<h4>Interview Pool: <%= @matches.count %> jobseekers</h4>
		</div>
		<div class="container-fluid" style="font-size: 15px;">
		    <div class="row">
		    	<% @matches.each do |match|%>
			        <div class="col-sm-6 col-lg-3 py-2">
			            <div class="card h-100" style="background-color: lightgreen">
			            	<img class="card-img-top img-fluid" src="https://upload.wikimedia.org/wikipedia/commons/b/b8/YouTube_Logo_2017.svg" alt="Card image cap">
			                <div class="card-body">
			                    <h4 class="card-title">Candidate Number: <%= match.jobseeker.id %></h4>
			                    <p class="card-text">
									Degree in: <%= match.jobseeker.degree.name %><br>
									University: <%= match.jobseeker.university.name %><br>
									Latest CGPA: <%= match.jobseeker.cgpa %><br>
									Knowledge Score: <%= match.jobseeker.knowledge_score %>%<br>
									Skill Score: <%= match.jobseeker.skill_score %>%<br>
									Activity Score: <%= match.jobseeker.activity_score %>%<br>
			                    	</p>
			                    <p class="card-text"><small class="text-muted">Last Updated: <%= match.jobseeker.created_at.to_date %></small></p>
			                </div>
			            </div>
			        </div>
			    <% end %>
		    </div>
		</div>
	</div>

</div>

app/views/vacancies/show.html.erb
<div style="margin: 10px;">
	<div style="background-color: yellow">
		<h3>NOTES FOR DEMONSTRATION</h3>
		<ol>
				<li>Recruiter can use all the filtering abilities to find the right person before they add who they like into the cart</li>
				<li>They are many more filtering. This demo only showed based on 4 areas</li>
				<li>Key to the filtering is fast and multidimensional. Demo product is a basic one which is 1 dimensional</li>
		</ol>
	</div>

	<div>
		<h3>Company Profile</h3>
		<div style="margin-bottom: 5px;">
			Name: <%= @company.name %><br>
			Industry: <%= @company.industry.name %><br>
			Size: <%= @company.workforce_size %><br>
			Preference of talent work hours: <%= @company.work_hours %><br>
			Preference of talent strength: <%= @company.strength %><br>
		</div>
	</div>

	<br>

	<div>
		<h3>Vacancy Details</h3>
		<div style="margin-bottom: 5px;">
			Role: <%= @vacancy.name %><br>
			Description: <%= @vacancy.description %><br>
			Department: <%= @vacancy.department %><br>
			Quantity Needed: <%= @vacancy.quantity %><br>
		</div>
	</div>

	<div style="border: 2px blue solid; padding: 10px;">
			<h4><%= @vacancy.name %></h4>
			<div>
				<div class="text-center">
					<h6>Filters in Action</h6>
				</div>

				<div class="row" style="margin: 10px;">
					<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
						Based in <%= @company.state.name %>
					</div>
					<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
						>1 working experience in <%= @company.industry.name %>
					</div>

					<% if params[:degree] %>
						<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
							Degree in <%= Industry.find(params[:degree]).name %>
						</div>
					<% end %>
					<% if params[:knowledge] %>
						<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
							High knowledge in <%= Topic.find(params[:knowledge]).name %>
						</div>
					<% end %>
					<% if params[:skill] %>
						<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
							High Skill in <%= Skill.find(params[:skill]).name %>
						</div>				
					<% end %>
					<% if params[:activity] %>
						<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
							Active in <%= Activity.find(params[:activity]).name %>
						</div>				
					<% end %>
				</div>
			</div>

			<div class="container-fluid" style="font-size: 15px;">
			    <div class="row">
					<div class="col-sm-6 col-lg-3 py-2">
						<div class="container-fluid">
							<div class="row" style="margin: 10px;">
								<h4>Degree:</h4>
								<% @degrees.each do |degree| %>
									<%= form_tag vacancy_path(params[:id]), :method => "get" do %>
										<%= hidden_field_tag  :degree, degree.id %>
										<%= submit_tag degree.name, :name => nil %>
									<% end %>
								<% end %>
							</div>
						</div>
					</div>
					<div class="col-sm-6 col-lg-3 py-2">
						<div class="container-fluid">
							<div class="row" style="margin: 10px;">
								<h4>Top Knowledge:</h4>
									<% @knowledges.each do |knowledge| %>
										<%= form_tag vacancy_path(params[:id]), :method => "get" do %>
											<%= hidden_field_tag  :knowledge, knowledge.id %>
											<%= submit_tag knowledge.name, :name => nil %>
										<% end %>
									<% end %>
							</div>
						</div>
					</div>
					<div class="col-sm-6 col-lg-3 py-2">
						<div class="container-fluid">
							<div class="row" style="margin: 10px;">
								<h4>Top Skill:</h4>
									<% @skills.each do |skill| %>
										<%= form_tag vacancy_path(params[:id]), :method => "get" do %>
											<%= hidden_field_tag  :skill, skill.id %>
											<%= submit_tag skill.name, :name => nil %>
										<% end %>
									<% end %>
							</div>
						</div>
					</div>
					<div class="col-sm-6 col-lg-3 py-2">
						<div class="container-fluid">
							<div class="row" style="margin: 10px;">
								<h4>Top Activity:</h4>
									<% @activities.each do |activity| %>
										<%= form_tag vacancy_path(params[:id]), :method => "get" do %>
											<%= hidden_field_tag  :activity, activity.id %>
											<%= submit_tag activity.name, :name => nil %>
										<% end %>
									<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="text-center">
				<h4>Total candidates in your pool: <%= @matches.count %></h4>
				<div class="btn btn-success" style="font-size: 30px">
					<%= link_to "Set interview questions!", vacancy_interview_path(@vacancy) %>
				</div>
			</div>
			<br>
			<div class="text-center">
				<h4>Total candidates matching filters: <%= @jobseekers.count %></h4>
			</div>
			<div class="container-fluid" style="font-size: 15px;">
			    <div class="row">
			    	<% @jobseekers.each do |jobseeker|%>
				        <div class="col-sm-6 col-lg-3 py-2">
				            <div class="card h-100" style="background-color: rgb(173, 188, 201)">
				                <div class="card-body">
				                    <h4 class="card-title">Candidate Number: <%= jobseeker.id %></h4>
				                    <p class="card-text">
										Degree in: <%= jobseeker.degree.name %><br>
										University: <%= jobseeker.university.name %><br>
										Latest CGPA: <%= jobseeker.cgpa %><br>
										Location: <%= jobseeker.location.name %><br>
										Prefers to work in <%= jobseeker.pref_size %> company<br>
										Prefers to work  in <%= jobseeker.pref_hours %> hours<br>
										Has worked for companies in:
											<li><%= jobseeker.we1.name %></li>
											<li><%= jobseeker.we2.name %></li>
											<li><%= jobseeker.we3.name %></li>
										Knowledge Score: <%= jobseeker.knowledge_score %>%<br>
										Skill Score: <%= jobseeker.skill_score %>%<br>
										Activity Score: <%= jobseeker.activity_score %>%<br>
				                    	</p>
				                    <p class="card-text"><small class="text-muted">Last Updated: <%= jobseeker.created_at.to_date %></small></p>
				                    	<% if jobseeker.ok_1? && jobseeker.ok_2?%>
			                    			<a href="#" class="btn btn-success" style="margin: 2px;">Reference Checked Out - 2</a>
			                    		<% elsif jobseeker.ok_1? || jobseeker.ok_2?%>
			                    			<a href="#" class="btn btn-success" style="margin: 2px;">Reference Checked Out - 1</a>			                    
			                    		<% end %>
				                    	<div>
				                    		<a href='/jobseekers/<%=jobseeker.id%>' class="btn btn-primary" style="margin: 2px;">Check Profile</a>
				                    	</div>
										<div>
											<% if JobseekerVacancy.where(vacancy_id: params[:id]).where(jobseeker_id: jobseeker.id).exists? %>
												Remove this candidate from your pool!
											<% else %>
												<div class="btn btn-primary">
													<%=form_for(@match, url:create_match_path(@vacancy), method: 'post') do |form|%>
													<div>
														<!-- Hidden text field carrying variable unrelated to mode -->
														<%= form.hidden_field :jobseeker_id, :value => jobseeker.id %>
													</div>	 
													<%=form.submit "I like this candidate"%>
													<% end %>
												</div>
											<% end %>					
										</div>
				                </div>
				            </div>
				        </div>
				    <% end %>
			    </div>
			</div>
	</div>
</div>