config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'generic#landing'

	# These routes will be for signup. The first renders a form in the browse, the second will 
	# receive the form and create a user in our database using the data given to us by the user.
	post '/recruiters' => 'recruiters#create'

	post '/login' => 'sessions#create', :as => :create_session
	get '/logout' => 'sessions#destroy'

	resources :companies do
	end

	resources :vacancies do
		get '/interview' => 'vacancies#interview', :as => :interview
		get '/interview/results' => 'vacancies#results', :as => :interview_results
	end

	post '/vacancies/:vacancy_id/jobseeker_vacancies' => 'jobseeker_vacancies#create', :as => :create_match

	resources :jobseekers do
	end
end

app/models/company.rb
class Company < ApplicationRecord
	enum workforce_size: [:no_answer, :less_than_20, :more_than_20] 
	enum work_hours: [:no_preference, :nine_to_nine, :work_at_home] 
	enum strength: [:no_preference_2, :academic, :extra_curricular]

	belongs_to :recruiter
	belongs_to :industry
	belongs_to :state
	has_many :vacancies

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	def new	
		@company = Company.new	
	end

	def create
		@company = Company.new(company_params)
		@company.recruiter_id = current_recruiter.id
		if @company.save
			redirect_to company_path(@company)
		else
			redirect_back(fallback_location: root_path)
		end
	end

	def show
		@company = Company.find(params[:id])
		if @company.less_than_20? && @company.nine_to_nine?
			@jobseekers = Jobseeker.where("pref_size LIKE (?)", "Small").where("pref_hours LIKE (?)", "Traditional").where(location_id: @company.state).where(degree_id: @company.industry).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
		elsif @company.less_than_20? && @company.work_at_home?
			@jobseekers = Jobseeker.where("pref_size LIKE (?)", "Small").where("pref_hours LIKE (?)", "Modern").where(location_id: @company.state).where(degree_id: @company.industry).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
		elsif @company.more_than_20? && @company.work_at_home?
			@jobseekers = Jobseeker.where("pref_size LIKE (?)", "Big").where("pref_hours LIKE (?)", "Modern").where(location_id: @company.state).where(degree_id: @company.industry).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
		elsif @company.more_than_20? && @company.nine_to_nine?
			@jobseekers = Jobseeker.where("pref_size LIKE (?)", "Big").where("pref_hours LIKE (?)", "Traditional").where(location_id: @company.state).where(degree_id: @company.industry).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
		else
			@jobseekers = Jobseeker.where(location_id: @company.state).where(degree_id: @company.industry).where("we1_id LIKE (?) OR we2_id LIKE (?) or we3_id LIKE (?)", @company.industry, @company.industry, @company.industry)
		end

		@vacancies = Vacancy.where(company_id: params[:id])

	end

	private

	def company_params
	  params.require(:company).permit!
	end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/new.html.erb
<div style="background-color: yellow; margin: 10px; margin-bottom: 30px;">
	<h6>NOTES FOR DEMONSTRATION</h6>
	<ol style="font-size: 15px">
		<li>Upon sign up, we can (should) validate the recruiter either by calling them or call their company.</li>
		<li>Optional - We can even fill up this page for them during the call.</li>
		<li>Main recruiter should also be able to list down their colleagues (give email and temp password) who have access to that company</li>
		<li>The filters below will be the most basic filter in all the searches!</li>
	</ol>
	<h6>Process: User sign up > User receives a call > User gets authorisation code > user go to this page</h6>
</div>

<div style="margin: 20px;">
	<div>
		<h1>Company Profile</h1>
		<h4>Tell us what generally matters to your company!</h4>
	</div>

	<div >
		<div>
			<%=form_for @company do |form|%>
				<div>
					<%= form.label :name %> 
					<%= form.text_field :name, placeholder: 'Name of Company' %>
				</div>
				
				<div>
					Company mission: (1 line to describe what your company mission is)
				</div>
				
				<div>
					<%= form.label :state %> 
					<%= form.collection_select :state_id, State.all, :id, :name, :prompt => "Choose your state" %>
				</div>

				<div>
					<%= form.label :industry %> 
					<%= form.collection_select :industry_id, Industry.all, :id, :name, :prompt => "Choose your industry" %>
				</div>

				<div>
					<%= form.label :workforce_size, 'Size of Company' %>
					<%= form.select :workforce_size, Company.workforce_sizes.keys.to_a %>

				</div>

				<div>
					<%= form.label :work_hours, 'What time committment does your employer possess?' %>
					<%= form.select :work_hours, Company.work_hours.keys.to_a %>

				</div>

				<div>
					<%= form.label :strength, 'Do you prefer a booksmart or streetsmart people?' %>
					<%= form.select :strength, Company.strengths.keys.to_a %>

				</div>	

			<div style="margin: 10px">
				<%=form.submit "Set up my company!"%>
			</div>
			<% end %>		
		</div>

	</div>
</div>

app/views/companies/show.html.erb
<div style="margin: 10px;">

	<div style="background-color: yellow">
		<h3>NOTES FOR DEMONSTRATION</h3>
		<ol>
			<li>This is the main page. In normal day, this is the first page after recruiter login</li>
			<li>Recruiter can do 2 key things: 1)Set general filters for their companies and see who matched them 2)Create a specific vacancy</li>
			<li>Any company will get to see which candidates that match their general filters and like their company. For free.</li>
			<li>Company can add more filters to this general pool at any point of time</li>
			<li>Jobseeker: Whoever matches these filters will see the company details on their mobile app.</li>
		</ol>
	</div>

	<div>
		<h3>Company Profile</h3>
		<div style="margin-bottom: 10px;">
			Name: <%= @company.name %><br>
			State: <%= @company.state.name %><br>
			Industry: <%= @company.industry.name %><br>
			Size: <%= @company.workforce_size %><br>
			Preference of talent work hours: <%= @company.work_hours %><br>
			Preference of talent strength: <%= @company.strength %><br>
		</div>
		<h6>(Edit Company) - Tell us more about your company!</h6>
	</div>

	<br>

	<div style="border: 2px blue solid; padding: 10px;">
		<h4>Your Vacancies!</h4>
		<% if @vacancies.count == 0%>
			<div>
				You have no vacancy yet.
			</div>
		<% end %>

		<div>
			<% @vacancies.each do |v| %>
				<div style="border: 2px solid blue; padding: 5px;">
					Name of role: <%= v.name %><br>
					Description: <%= v.description %><br>
					Department: <%= v.department %><br>
					Quantity: <%= v.quantity %><br>
					Size of talent pool: <%= v.jobseekers.count %> jobseekers<br>
					Created at: <%= v.created_at.to_date %><br>
					<br>

					<div class="container-fluid" style="font-size: 15px;">
					    <div class="row">
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightblue">
					                <div class="card-body">
					                    <h4 class="card-title">Question 1</h4>
					                    <p class="card-text">
					                    	"<%= v.question_1 %>"<br>
											<%= v.q1_time %>s<br>
					                    	</p>
					                </div>
					            </div>
					        </div>
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightblue">
					                <div class="card-body">
					                    <h4 class="card-title">Question 2</h4>
					                    <p class="card-text">
					                    	"<%= v.question_2 %>"<br>
											<%= v.q2_time %>s<br>
					                    	</p>
					                </div>
					            </div>
					        </div>
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightblue">
					                <div class="card-body">
					                    <h4 class="card-title">Question 3</h4>
					                    <p class="card-text">
					                    	"<%= v.question_3 %>"<br>
											<%= v.q3_time %>s<br>
					                    	</p>
					                </div>
					            </div>
					        </div>
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightblue">
					                <div class="card-body">
					                    <h4 class="card-title">Question 4</h4>
					                    <p class="card-text">
					                    	"<%= v.question_4 %>"<br>
											<%= v.q4_time %>s<br>
					                    	</p>
					                </div>
					            </div>
					        </div>
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightblue">
					                <div class="card-body">
					                    <h4 class="card-title">Question 5</h4>
					                    <p class="card-text">
					                    	"<%= v.question_5 %>"<br>
											<%= v.q5_time %>s<br>
					                    	</p>
					                </div>
					            </div>
					        </div>	
					        <div class="col-sm-4 col-lg-2 py-2 text-center">
					            <div class="card h-100" style="background-color: lightgreen; font-size: 40px;">
									<% if v.question_1 =! nil %>
										<%= link_to "Get your result!", vacancy_interview_results_path(v) %>
									<% else %>
										<%= link_to "Check out this vacancy", vacancy_path(v) %>
									<% end %>
					            </div>
					        </div>		        		        		        
					    </div>
					</div>
				<% end %>
			</div>
			<div class="btn btn-outline-primary" style="margin-top: 10px;">
				<h3><%= link_to "Create New Vacancy", new_vacancy_path %></h3>
			</div>
		</div>
	</div>

	<br>	

	<div style="border: 2px blue solid; padding: 10px;">
		<h4>General Pool!</h4>
		<div>
		
		<div class="text-center">
			<h6>Filters in Action</h6>
		</div>

			<div class="row" style="margin: 10px;">
				<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
					Based in <%= @company.state.name %>
				</div>
				<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
					Prefers to work in size <%= @company.workforce_size %> company
				</div>
				<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
					Degree in <%= @company.industry.name %>
				</div>
				<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
					>1 working experience in <%= @company.industry.name %>
				</div>
				<div class="btn btn-outline-primary" style="margin: 2px 5px; color: black">
					Prefers the working style of <%= @company.work_hours %>
				</div>
				<div class="btn btn-outline-danger" style="margin: 2px 5px; color: black">
					<h6>Add more general filters</h6>
				</div>
			</div>
			
		</div>
		<div class="text-center">
			<h6><%=@jobseekers.count%> candidate(s) matched your general filters and liked you back!</h6>
		</div>
		<div class="container-fluid" style="font-size: 15px;">
		    <div class="row">
		    	<% @jobseekers.each do |jobseeker|%>
			        <div class="col-sm-6 col-lg-3 py-2">
			            <div class="card h-100" style="background-color: rgb(173, 188, 201)">
			                <div class="card-body">
			                    <h4 class="card-title">Candidate Number: <%= jobseeker.id %></h4>
			                    <p class="card-text">
									Degree in: <%= jobseeker.degree.name %><br>
									University: <%= jobseeker.university.name %><br>
									Latest CGPA: <%= jobseeker.cgpa %><br>
									Location: <%= jobseeker.location.name %><br>
									Prefers to work in <%= jobseeker.pref_size %> company<br>
									Prefers to work  in <%= jobseeker.pref_hours %> hours<br>
									Has worked for companies in:
										<li><%= jobseeker.we1.name %></li>
										<li><%= jobseeker.we2.name %></li>
										<li><%= jobseeker.we3.name %></li>
									Knowledge Score: <%= jobseeker.knowledge_score %>%<br>
									Skill Score: <%= jobseeker.skill_score %>%<br>
									Activity Score: <%= jobseeker.activity_score %>%<br>
			                    	</p>
			                    <p class="card-text"><small class="text-muted">Last Updated: <%= jobseeker.created_at.to_date %></small></p>
			                    	<% if jobseeker.ok_1? && jobseeker.ok_2?%>
			                    		<a href="#" class="btn btn-success" style="margin: 2px;">Reference Checked Out - 2</a>
			                    	<% elsif jobseeker.ok_1? || jobseeker.ok_2?%>
			                    		<a href="#" class="btn btn-success" style="margin: 2px;">Reference Checked Out - 1</a>			                    
			                    	<% end %>
			                    	<a href="#" class="btn btn-primary" style="margin: 2px;">Check Jobseeker Out</a>
			                    	<a href="#" class="btn btn-primary" style="margin: 2px;">Add to Pool</a>
			                </div>
			            </div>
			        </div>
			    <% end %>

		    </div>
		</div>

</div>